### ISSUE TITLE
Bibliography not printing

### ISSUE THREAD

**Issue by IndianaTones** [PierreSenellart/erc-latex-template#3]
Hello Pierre and thank you for such a nice-looking and easy to use template!  My only issue is that while the references are cited properly throughout the text, the bibliography does not show up. Thanks in advance!

**Comment by PierreSenellart** [comment]
It should be enough to just add `\printbibliography` at the appropriate place. Please let me know if this works for you, otherwise I'd be happy to look at a complete example where the problem occurs (which can be sent by email if you can't make it public).

**Comment by IndianaTones** [comment]
Thanks for the swift reply! 

Here are the relevant lines as drawn from the template:

`\defbibheading{subsection}[\bibname]{\subsection*{#1}}`
`\printbibliography[prenote=bolditalics,heading=subsection]`

It is likely that I am missing something simple - apologies for the trouble.

**Comment by popgenomics** [comment]
Hello Pierre,
and thank you very much for sharing this package, it's very usefull.
I'm sorry to bother you with this issue, but I have some problem to display the bibliography.

I'm using the last version, without modifying the code, I just filled the parts. But the bibliography is not formatted within the text, in the pdf it's shown as follows:
> ... following the method developped by (**stoffel2016inbreedr**).

And there is bibliography printed at the end of document despite the following lines at the end:
```
\section{Resources}
\label{sec:resources}
\input{parts/resources}

\pagebreak
\bigskip
\printbibliography[prenote=bolditalics]

\end{document}

```

I compiled from the part-B2 subdirectory as follows:
`pdflatex erc-B2.tex; bibtex erc-B2; pdflatex erc-B2.tex; pdflatex erc-B2.tex`

Do you have an idea about what I have to do please?

All the best,

Camille

EDIT #1 : I think the issue is because I don't have  `\RequirePackage[style=authoryear]{biblatex} ` installed on my laptop....I'm currently checking if it's effectively the issue.

**Comment by PierreSenellart** [comment]
Try using biber instead of bibtex, biber is a more modern tool that works with `biblatex`. And yes, you definitely need to have `biblatex` installed.

**Comment by popgenomics** [comment]
Thank you very much! For reasons I don't understand, I couldn't make the link between `biblatex` and this document on my laptop...
But by migrating the whole erc-latex project to `Overleaf`, it works perfectly, with all bibliographic styles present in Overleaf.
Thank you very much again!
